Added --enable-cvsbuild for nightly snapshots

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB LEX LEXLIB LEX_OUTPUT_ROOT YACC CXXCPP EGREP LIBOBJS build build_cpu build_vendor build_os host host_cpu host_vendor host_os LIBM LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE NO_CVSBUILD_TRUE NO_CVSBUILD_FALSE CVSBUILD CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB LEX LEXLIB LEX_OUTPUT_ROOT YACC CXXCPP EGREP LIBOBJS build build_cpu build_vendor build_os host host_cpu host_vendor host_os LIBM LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -857,6 +857,7 @@ Optional Features:
   --enable-profile        Turn on compiler profiling information (default=no)
   --enable-extrawarning   Turn on compiler extra warning information (default=no)
   --enable-static         Turn on linking libraries staticly (default=no)
+  --enable-cvsbuild Create nightly build
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
 
@@ -1754,6 +1755,29 @@ fi;
 
 CXXFLAGS="${CXXFLAGS} ${MYCXXFLAGS} ${INCL}"
 CCFLAGS="${CCFLAGS} ${MYCCFLAGS} ${INCL}"
+
+# Check whether --enable-cvsbuild or --disable-cvsbuild was given.
+if test "${enable_cvsbuild+set}" = set; then
+  enableval="$enable_cvsbuild"
+  case "${enableval}" in
+  no)  cvsbuild=false ;;
+  *) cvsbuild=${enableval} ;;
+esac
+else
+  debug=false
+fi;
+
+
+if test x$cvsbuild = xfalse; then
+  NO_CVSBUILD_TRUE=
+  NO_CVSBUILD_FALSE='#'
+else
+  NO_CVSBUILD_TRUE='#'
+  NO_CVSBUILD_FALSE=
+fi
+
+CVSBUILD=$cvsbuild
+
 
 # Checks for programs.
 for ac_prog in gawk mawk nawk awk
@@ -6226,6 +6250,13 @@ LIBOBJS=$ac_libobjs
 LTLIBOBJS=$ac_ltlibobjs
 
 
+if test -z "${NO_CVSBUILD_TRUE}" && test -z "${NO_CVSBUILD_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"NO_CVSBUILD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"NO_CVSBUILD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -6809,6 +6840,9 @@ s,@ac_ct_STRIP@,$ac_ct_STRIP,;t t
 s,@INSTALL_STRIP_PROGRAM@,$INSTALL_STRIP_PROGRAM,;t t
 s,@AWK@,$AWK,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
+s,@NO_CVSBUILD_TRUE@,$NO_CVSBUILD_TRUE,;t t
+s,@NO_CVSBUILD_FALSE@,$NO_CVSBUILD_FALSE,;t t
+s,@CVSBUILD@,$CVSBUILD,;t t
 s,@CXX@,$CXX,;t t
 s,@CXXFLAGS@,$CXXFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
